# -*- coding: utf-8 -*-
"""O que tem de interessante em cada atração: 2 a 3 itens curtos, separados por ' · '.
Chave = começo do nome da atração no guia (sem acento não importa; casa por 'começa com')."""

DESTAQUES = {
# ---------------- MADRI ----------------
"Museo del Prado": "Las Meninas, de Velázquez · As Pinturas Negras de Goya · O Jardim das Delícias, de Bosch",
"Museo Reina Sofía": "Guernica, de Picasso · Salas de Dalí e Miró · Elevadores de vidro com vista",
"Palacio Real": "Sala do Trono e salão de banquetes · Armaria Real · Pátio com vista da Casa de Campo",
"Catedral de la Almudena": "Teto colorido, diferente de qualquer catedral · Cripta neorromânica · Subida à cúpula com vista",
"Jardines de Sabatini": "Espelho d'água com o palácio ao fundo · Cercas-vivas geométricas · Pôr do sol",
"Templo de Debod": "Templo egípcio de 2.200 anos · Reflexo no espelho d'água · Mirante para o Palácio Real",
"Parque del Retiro": "Lago com barcos a remo · Palacio de Cristal · Estátua do Anjo Caído",
"Puerta de Alcalá": "Arco de 1778 com cinco vãos · Uma face diferente da outra · Entrada do Retiro em frente",
"Fuente de Cibeles": "A fonte da deusa, onde o Real Madrid comemora · Mirador no 8º andar do palácio · Exposições grátis no CentroCentro",
"Gran Vía": "Edifício Metrópolis e Edifício Telefónica · Letreiro da Schweppes na Plaza del Callao · Primark de cinco andares",
"Puerta del Sol": "Estátua do Urso e do Medronheiro · Marco do Quilômetro Zero · Arcos e afrescos da Plaza Mayor",
"Mercado de San Miguel": "Estrutura de ferro e vidro de 1916 · Bancas de tapas, ostras e jamón · Come-se em pé, de banca em banca",
"El Corte Inglés Callao": "Terraço no 9º andar, grátis · Vista do letreiro da Schweppes e da Gran Vía · Praça de alimentação gourmet",
"El Rastro": "Feira de rua aos domingos, das 9h às 15h · Antiguidades nas ruas laterais · Tapas em La Latina na saída",
"Tour do Estádio": "Museu e sala de troféus · Vista do gramado da arquibancada · Loja oficial",
"Bate-volta a Toledo": "Catedral gótica · Mirador del Valle, a vista clássica · Ruelas medievais e marzipã",
"Plaza de España": "Monumento a Cervantes com Dom Quixote · Jardins renovados · Edifício España e Torre de Madrid",
"Mirante do Hotel Riu": "Terraço 360° no 27º andar · Passarela de vidro · Pôr do sol sobre a Gran Vía",
"Edifício Metrópolis": "Cúpula com a Vitória alada · A foto clássica da Gran Vía · Iluminado à noite",
"Museu Thyssen": "Do gótico à pop art num só prédio · Van Gogh, Monet e Hopper · Visita mais leve que a do Prado",
"Cava Baja": "Tavernas centenárias lado a lado · Tapas de balcão em balcão · Casas com varandas de madeira",
"Malasaña": "Brechós e lojas vintage · Plaza del Dos de Mayo · Cafés e bares de rua",
"Casa del Libro": "Livraria de vários andares · Janela com vista da Gran Vía · Seção de livros em inglês",
"HOFF": "Bancada para montar o tênis com miçangas · Modelos só desta loja",
"Barro": "Aula avulsa no torno · Leva-se a peça para casa",
"Nomad Museo": "Salas de projeção imersiva · Bom programa para dia de chuva",
"Alcalá de Henares": "Universidade do século XV · Casa natal de Cervantes · Calle Mayor com arcadas",
"UNOGRAPHY": "Estúdio de autorretrato no estilo coreano · Fotos impressas na hora",
"Palacio de Cristal": "Pavilhão todo de vidro e ferro, de 1887 · Exposições do Reina Sofía, grátis · Lago com ciprestes dentro d'água",
"Estação de Atocha": "Jardim tropical com palmeiras no saguão antigo · Estrutura de ferro de 1892 · Memorial do 11-M",
"Real Jardín Botánico": "Estufas tropicais e de deserto · Coleção de bonsais · Terraços do século XVIII",
"CaixaForum": "Jardim vertical de 24 m na rua · Prédio que parece flutuar · Escada interna escultural",
"Círculo de Bellas Artes": "Terraço com a estátua de Minerva · Vista da Gran Vía e do Metrópolis · Café no térreo",
"Plaza de Oriente": "Estátua equestre de Felipe IV · Fileira de reis de pedra · Fachada do Teatro Real",
"Plaza de la Villa": "Casa e Torre de los Lujanes, do século XV · Antiga prefeitura · Um dos cantos mais antigos da cidade",
"Plaza de Santa Ana": "Teatro Español · Terraços de bar o ano todo · Frases de escritores gravadas no chão",
"Monasterio de las Descalzas": "Escadaria coberta de afrescos · Tapeçarias desenhadas por Rubens · Capelas no claustro",
"San Francisco el Grande": "Cúpula de 33 m de diâmetro · Capela com pintura de Goya · Interior todo decorado",
"Ermita de San Antonio": "Cúpula pintada por Goya · Túmulo do pintor · Espelhos para ver os afrescos",
"Museo Sorolla": "Ateliê do pintor como ele deixou · Quadros de praia cheios de luz · Jardim andaluz",
"Museo Cerralbo": "Salão de baile espelhado · Armaduras e relógios · Escadaria de honra",
"Palacio de Liria": "Biblioteca com cartas de Colombo · Retratos de Goya e Velázquez · Salões ainda habitados",
"Museo Arqueológico": "A Dama de Elche · Réplica da caverna de Altamira · Tesouro visigodo de Guarrazar",
"Campo del Moro": "Gramado com o palácio no alto · Fontes e pavões · Trilhas arborizadas",
"Madrid Río": "Ponte em espiral de Perrault · Ponte de Segóvia, do século XVI · Quilômetros de passeio plano",
"Matadero Madrid": "Galpões de tijolo de 1911 · Exposições e cinema · Mercado de produtores em alguns fins de semana",
"Teleférico de Madrid": "11 minutos por cima do rio · Vista do Palácio Real e da Almudena · Chega à Casa de Campo",
"Faro de Moncloa": "Mirante envidraçado a 92 m · Vista da serra nevada no inverno · Elevador panorâmico",
"Estação fantasma": "Plataforma de 1919 intacta · Anúncios de azulejo originais · Trens passam sem parar",
"Las Ventas": "Fachada de tijolo em estilo mourisco · Museu taurino · Visita à arena com audioguia",
"Parque de El Capricho": "Jardins inglês, francês e italiano · Bunker da Guerra Civil · Laguinho com cisnes",
"Bate-volta Segóvia": "Aqueduto romano de 167 arcos · Alcázar de conto de fadas · Leitão assado",
"Bate-volta El Escorial": "Panteão dos reis · Biblioteca com afrescos · Basílica e pátios",
# ---------------- ROMA ----------------
"Coliseu": "Arena e subterrâneos · Via Sacra e arcos do Fórum · Vista do Palatino sobre o Circo Massimo",
"Museus Vaticanos": "Capela Sistina · Salas de Rafael · Galeria dos Mapas",
"Basílica de São Pedro": "A Pietà de Michelangelo · Baldaquino de Bernini · Subida à cúpula",
"Audiência Geral": "O Papa passa de papamóvel · Bênção no fim · Colunata de Bernini",
"Panteão": "Cúpula com o óculo aberto · Túmulo de Rafael · Piso de mármore original",
"Fontana di Trevi": "Netuno e os cavalos-marinhos · A moeda por cima do ombro · Mais vazia de manhã cedo",
"Galleria Borghese": "Apolo e Dafne, de Bernini · Paulina Bonaparte, de Canova · Sala dos Caravaggios",
"Castel Sant'Angelo": "Terraço com vista de São Pedro · Aposentos papais · Ponte dos anjos de Bernini",
"Piazza di Spagna": "Escadaria de 135 degraus · Fonte da Barcaccia · Vitrines da Via Condotti",
"Piazza Navona": "Fonte dos Quatro Rios, de Bernini · Igreja de Sant'Agnese · Artistas de rua",
"Vittoriano": "Terraço panorâmico de elevador · Túmulo do Soldado Desconhecido · Vista do Fórum e do Coliseu",
"Circo Massimo": "A pista das corridas de biga · Vista do Palatino · Gramado para descansar",
"Porta Maggiore": "Dois aquedutos sobrepostos · Túmulo do padeiro Eurisace · Muralha Aureliana",
"Stadio Olimpico": "Casa da Roma e da Lazio · Foro Itálico com estátuas de mármore",
"Trastevere": "Ruelas de pedra com roupa no varal · Santa Maria in Trastevere · Trattorias e bares à noite",
"Campo de' Fiori": "Feira de manhã · Estátua de Giordano Bruno · Bares à noite",
"Piazza del Popolo": "Obelisco egípcio de Ramsés II · Igrejas gêmeas · Dois Caravaggios em Santa Maria del Popolo",
"Terrazza del Pincio": "Vista da Piazza del Popolo · Cúpula de São Pedro ao fundo · Pôr do sol",
"Jardim das Laranjeiras": "Mirante sobre o Tibre · Laranjeiras e pinheiros · Basílica de Santa Sabina ao lado",
"Buraco da fechadura": "A cúpula de São Pedro emoldurada por um jardim · Praça desenhada por Piranesi",
"Bocca della Verità": "A máscara de mármore do filme A Princesa e o Plebeu · Igreja medieval de Santa Maria in Cosmedin",
"São João de Latrão": "Estátuas gigantes dos apóstolos · Claustro com colunas retorcidas · Scala Santa em frente",
"Santa Maria Maggiore": "Mosaicos do século V · Teto dourado · Túmulo de Bernini e do Papa Francisco",
"San Pietro in Vincoli": "O Moisés de Michelangelo · As correntes de São Pedro",
"Santa Maria in Trastevere": "Mosaicos dourados na abside · Colunas de templos romanos · Praça com fonte",
"San Luigi dei Francesi": "Três telas de Caravaggio sobre São Mateus · Luz acende com moeda",
"Sant'Ignazio": "Teto que parece abrir para o céu · Cúpula falsa, pintada · Espelho para a foto",
"Santa Maria della Vittoria": "O Êxtase de Santa Teresa, de Bernini · Interior barroco dourado",
"Basílica de San Clemente": "Igreja do século XII · Embaixo, uma igreja do século IV · Mais embaixo, templo de Mitra e rua romana",
"Piazza del Campidoglio": "Piso em estrela de Michelangelo · Estátua de Marco Aurélio · Vista do Fórum pelos fundos",
"Museus Capitolinos": "A Loba Capitolina · Marco Aurélio original · Galeria com vista do Fórum",
"Mercados de Trajano": "Galerias em semicírculo · Coluna de Trajano ao lado · Vista dos Fóruns Imperiais",
"Termas de Caracalla": "Paredes de 30 m de altura · Mosaicos no piso · Quase sem fila",
"Via Appia Antica": "Calçamento romano original · Catacumbas de São Calisto e São Sebastião · Túmulo de Cecília Metela",
"Gianicolo": "Roma inteira de cima · Tiro de canhão ao meio-dia · Estátua de Garibaldi",
"Fontana dell'Acqua Paola": "Fonte monumental de 1612 · Mirante em frente · Aparece no filme A Grande Beleza",
"Quartiere Coppedè": "Arco com lustre de ferro · Fonte das Rãs · Casas de conto de fadas",
"Pirâmide de Céstio": "Pirâmide de mármore de 36 m · Cemitério dos poetas Keats e Shelley · Colônia de gatos",
"Largo di Torre Argentina": "Quatro templos republicanos · O local do assassinato de César · Santuário de gatos",
"Gueto Judeu": "Pórtico de Otávia · Grande Sinagoga · Alcachofra frita na Via del Portico d'Ottavia",
"Ilha Tiberina": "Ponte Fabrício, de 62 a.C. · Ilha em forma de barco · Beira do rio a pé",
"Fontana delle Tartarughe": "Quatro rapazes e tartarugas de bronze · Pracinha silenciosa",
"Galleria Doria Pamphilj": "Galeria dos Espelhos · Retrato de Inocêncio X, de Velázquez · Dois Caravaggios",
"Galleria Sciarra": "Pátio com afrescos Art Nouveau · Cobertura de vidro e ferro",
"Cripta dos Capuchinhos": "Seis capelas decoradas com ossos de 4.000 frades · Museu dos capuchinhos",
"Centrale Montemartini": "Deuses de mármore diante de turbinas · Mosaicos de caça · Quase sem visitantes",
"Colosseo Quadrato": "Seis andares de arcos · Estátuas no térreo · Arquitetura dos anos 1930",
"Bate-volta Ostia Antica": "Teatro romano · Mosaicos da praça das corporações · Ruas, termas e tavernas",
"Bate-volta Tivoli": "Alameda das Cem Fontes · Fonte do Órgão · Villa Adriana ali perto",
# ---------------- VERONA ----------------
"Arena di Verona": "Anfiteatro do século I quase inteiro · Arquibancada de mármore rosa · Vista da Piazza Bra do alto",
"Casa di Giulietta": "A varanda · Estátua de bronze de Julieta · Recados de amor no pátio",
"Torre dei Lamberti": "84 m, de elevador ou 368 degraus · Vista dos telhados e do rio · Sinos medievais",
"Museo di Castelvecchio": "Castelo do século XIV · Estátua equestre de Cangrande · Passeio pelas muralhas",
"Castel San Pietro": "O mirante clássico de Verona · Funicular ou escadaria · Pôr do sol sobre o Ádige",
"Piazza delle Erbe": "Feira e afrescos nas fachadas · Fonte Madonna Verona · Arco com a costela de baleia",
"Basilica di San Zeno": "Portas de bronze do século XI · Retábulo de Mantegna · Cripta do casamento de Romeu e Julieta",
"Bate-volta Veneza": "Praça e Basílica de São Marcos · Ponte de Rialto · Vaporetto pelo Grande Canal",
"Bate-volta Sirmione": "Castelo dentro do lago · Grutas de Catulo · Ruelas e sorvete",
"Ponte Pietra": "Arcos romanos e medievais · Vista do Teatro Romano e do morro · Bonita ao entardecer",
"Teatro Romano": "Arquibancada do século I a.C. · Museu no antigo convento · Terraço com vista",
"Duomo de Verona": "Portal românico com grifos · Assunção de Ticiano · Batistério com pia de mármore",
"Sant'Anastasia": "São Jorge e a Princesa, de Pisanello · Os dois corcundas das pias · Teto florido",
"San Fermo Maggiore": "Teto de madeira em forma de casco · Igreja inferior românica · Afrescos de Pisanello",
"Giardino Giusti": "Alameda de ciprestes · Labirinto de buxo · Mirante no alto da gruta",
"Arche Scaligere": "Túmulos góticos ao ar livre · Estátuas equestres · Grade com o símbolo da escada",
"Porta Borsari": "Fachada romana de dois andares · Início do Corso Porta Borsari",
"Arco dei Gavi": "Arco do século I remontado pedra por pedra · Trecho de calçada romana",
"Ponte Scaligero": "Ameias em rabo de andorinha · Vista do rio dos dois lados · Tijolo vermelho",
"Piazza Bra": "A Arena · Calçadão do Liston com cafés · Portoni della Bra",
"Via Mazzini": "Lojas de marca · Piso de mármore · Termina na Piazza delle Erbe",
"Tomba di Giulietta": "Sarcófago de mármore vermelho · Claustro · Museu de afrescos",
"Casa di Romeo": "Fachada medieval com ameias · Placa com versos de Shakespeare",
"Santuário de Lourdes": "Vista de toda Verona e da curva do rio · Pôr do sol",
"Bate-volta Borghetto": "Moinhos d'água · Ponte Visconteo · Tortellini de Valeggio",
"Bate-volta Mântua": "Palazzo Ducale e a Camera degli Sposi · Palazzo Te · Cidade cercada por lagos",
"Bate-volta Pádua": "Afrescos de Giotto · Basílica de Santo Antônio · Prato della Valle",
"Bate-volta Vicenza": "Teatro Olimpico · Basílica Palladiana · Villa La Rotonda",
"Bate-volta Soave": "Castelo e muralhas · Adegas de vinho Soave",
# ---------------- INNSBRUCK ----------------
"Nordkette": "Funicular e teleféricos do centro a 2.256 m · Vista da cidade e dos Alpes · Neve no topo",
"Goldenes Dachl": "2.657 telhas de cobre dourado · Relevos de Maximiliano I · Museu pequeno no prédio",
"Hofburg Innsbruck": "Salão dos Gigantes · Aposentos de Maria Teresa · Capela",
"Bergisel": "Torre de Zaha Hadid · Vista do alto do trampolim · Café panorâmico",
"Maria-Theresien-Strasse": "Coluna de Santa Ana · Fachadas barrocas com as montanhas ao fundo · Calçadão de lojas",
"Altstadt": "Arcadas medievais · Fachadas pintadas · Vielas ao redor do Telhado de Ouro",
"Hofkirche": "28 estátuas de bronze em tamanho gigante · Túmulo de Maximiliano I · Capela de Prata",
"Swarovski Kristallwelten": "O gigante que cospe água · Câmaras de arte com cristais · Nuvem de cristal no jardim",
"Catedral de São Tiago": "Teto pintado em ilusão · Madonna de Cranach no altar · Túmulo do arquiduque Maximiliano III",
"Arco do Triunfo": "Um lado festivo e um lado de luto · Montanhas emolduradas pelo arco",
"Stadtturm": "148 degraus · Plataforma a 31 m · Vista dos telhados e da Nordkette",
"Marktplatz": "A vista das casas coloridas de Mariahilf · Beira do rio Inn",
"Markthalle": "Bancas de queijos e embutidos tiroleses · Flores · Lanches rápidos",
"Riesengasse": "Lojas de madeira entalhada · Lembrancinhas locais",
"Alpenzoo": "Cabritos-monteses, linces e ursos · Um dos zoológicos mais altos da Europa · Vista da cidade",
"Aqua Dome": "Piscinas termais ao ar livre · Bacias suspensas com vista dos Alpes · Saunas",
"Schloss Ambras": "Salão Espanhol · Gabinete de arte e curiosidades · Armaduras",
"Helblinghaus": "Fachada rococó cheia de estuque · Em frente ao Telhado de Ouro",
"Museu de Arte Popular": "Salas tirolesas de madeira entalhada · Presépios · Trajes típicos",
"Ferdinandeum": "Arte do Tirol, do gótico ao moderno · Rembrandt e Klimt",
"Basílica de Wilten": "Interior rococó em rosa e ouro · Imagem de Nossa Senhora sob as Quatro Colunas",
"Abadia de Wilten": "Fachada barroca vermelha e amarela · Gigantes de pedra na entrada",
"Tirol Panorama": "Pintura circular de 1.000 m² · Batalha de 1809 no Bergisel · Museu dos Kaiserjäger",
"Hofgarten": "Jardim do palácio · Pavilhão de música · Estufa de palmeiras",
"Hungerburg": "Estações desenhadas por Zaha Hadid · Mirante sobre a cidade · Ponto de partida de trilhas",
"Fundição de sinos": "Fundição em funcionamento · Sala onde se toca os sinos · 14 gerações da mesma família",
"Igreja dos Jesuítas": "Cúpula de 60 m · Cripta dos príncipes",
"Ottoburg": "Torre gótica de 1494 · Monumento aos heróis de 1809 em frente",
"Patscherkofel": "Teleférico até 1.965 m · Vista da Nordkette de frente · Pista olímpica",
"Bate-volta Hall": "Praça medieval · Torre da Casa da Moeda · Ruelas sem turistas",
"Bate-volta Seefeld": "Vila alpina · Igrejinha Seekirchl na neve · Trilhas de inverno",
# ---------------- VIENA ----------------
"Palácio de Schönbrunn": "Grande Galeria · Aposentos de Sisi e Francisco José · Jardins e Gloriette",
"Belvedere": "O Beijo, de Klimt · Salão de Mármore · Jardins em terraços",
"Hofburg": "Museu Sisi · Aposentos imperiais · Coleção de prataria",
"Catedral de Santo Estêvão": "Telhado de azulejos coloridos · Torre sul, 343 degraus · Catacumbas",
"Kunsthistorisches": "Torre de Babel, de Bruegel · Escadaria com pinturas de Klimt · Café sob a cúpula",
"Naschmarkt": "Bancas de comida do mundo todo · Prédios de Otto Wagner em frente · Feira de pulgas aos sábados",
"Wiener Staatsoper": "Fachada neorrenascentista · Arcadas · Telão ao vivo na lateral em algumas noites",
"Visita guiada": "Escadaria e salões · Vista do palco",
"Prater": "Roda-gigante de 1897 · Parque de diversões · Alameda Hauptallee",
"Albertina": "Aposentos dos Habsburgo · De Monet a Picasso · A Lebre, de Dürer",
"Karlskirche": "Cúpula com afrescos · Duas colunas em espiral · Espelho d'água em frente",
"MuseumsQuartier": "Pátio com os bancos coloridos · Museu Leopold e mumok · Cafés",
"Mahnmal": "Portal da Violência, de Hrdlicka · Fica atrás da Ópera · Lembra as vítimas do nazismo",
"Kohlmarkt": "Lojas de luxo · Confeitaria Demel · Vista da cúpula da Hofburg",
"Graben": "Coluna da Peste · Fachadas barrocas · Banheiros Art Nouveau subterrâneos",
"Peterskirche": "Cúpula barroca · Concertos de órgão grátis · Interior dourado",
"Wiener Rathaus": "Fachada neogótica · Pista de patinação no inverno · Mercado na praça",
"Wiener Eistraum": "Patinação no gelo em frente à prefeitura · Trilhas de gelo pelo parque · Barracas de comida",
"Hundertwasserhaus": "Fachada colorida sem linhas retas · Árvores saindo das janelas · Vila de lojas em frente",
"Biblioteca Nacional": "200 mil livros antigos · Cúpula com afrescos · Globos de Coronelli",
"Votivkirche": "Duas torres de 99 m · Vitrais · Museu no coro",
"Parlamento": "Fonte de Palas Atena · Colunata grega · Centro de visitantes novo",
"Burgtheater": "Escadarias com pinturas de Klimt · Fachada curva na Ringstrasse",
"Volksgarten": "Templo de Teseu · Monumento a Sisi · Roseiral",
"Stadtpark": "Estátua dourada de Johann Strauss · Kursalon · Lago com patos",
"Secession": "Cúpula de folhas douradas · Friso de Beethoven, de Klimt",
"Museu Leopold": "A maior coleção de Egon Schiele · Klimt · Vista do terraço do MQ",
"Museu de História Natural": "Vênus de Willendorf · Sala dos dinossauros · Cúpula e escadaria",
"Tesouro Imperial": "Coroa do Sacro Império · Coroa imperial austríaca · Lança Sagrada",
"Cripta Imperial": "149 Habsburgos · Sarcófago duplo de Maria Teresa · Túmulos de Sisi e Francisco José",
"Escola Espanhola": "Picadeiro barroco branco · Cavalos lipizzaners · Estábulos",
"Mozarthaus": "Onde ele escreveu As Bodas de Fígaro · Único apartamento de Mozart que sobrou em Viena",
"Haus der Musik": "Escada-piano · Regente virtual · Salas dos compositores",
"Ankeruhr": "Doze figuras históricas de cobre · Desfile com música ao meio-dia",
"Palais Ferstel": "Passagem com abóbadas · Fonte no pátio · Café Central",
"Igreja dos Jesuítas": "Cúpula pintada em ilusão · Colunas retorcidas de mármore",
"Palácio da Justiça": "Hall com escadaria e estátua da Justiça · Café no terraço com vista",
"Pavilhões de Otto Wagner": "Mármore branco, verde e ouro · Girassóis Art Nouveau",
"Gloriette": "Vista do palácio e de Viena · Café dentro da arcada",
"Zoológico de Schönbrunn": "Pandas-gigantes · Pavilhão imperial de 1759 · Casa da floresta tropical",
"Haus des Meeres": "Aquário em 11 andares · Tubarões e casa tropical · Terraço no topo",
"Augarten": "Duas torres antiaéreas · Manufatura de porcelana · Alamedas barrocas",
"Donauturm": "Mirante a 150 m · Café giratório · Parque do Danúbio",
"Kahlenberg": "Viena e o Danúbio de cima · Vinhedos · Igreja de São José",
"Grinzing": "Tabernas de vinho novo · Casas de vinicultor · Clima de vila",
"Cemitério Central": "Túmulos de honra dos músicos · Igreja Art Nouveau · Alamedas enormes",
"Gasometer": "Quatro gasômetros de tijolo de 1899 · Arquitetura moderna por dentro",
"Museu Sigmund Freud": "Sala de espera original · O consultório · Objetos pessoais",
"Bate-volta Bratislava": "Castelo sobre o Danúbio · Centro antigo de pedestres · Portão de São Miguel",
"Bate-volta Abadia de Melk": "Biblioteca barroca · Igreja dourada · Terraço sobre o Danúbio",
# ---------------- BUDAPESTE ----------------
"Parlamento Húngaro": "Escadaria dourada · Coroa de Santo Estêvão · Salão da cúpula",
"Castelo de Buda": "Galeria Nacional · Terraços com vista de Peste · Funicular",
"Bastião dos Pescadores": "Sete torres brancas · Vista do Parlamento · Terraços de baixo, grátis",
"Igreja de Matias": "Telhado de azulejos coloridos · Interior todo pintado · Torre",
"Basílica de Santo Estêvão": "Mirante na cúpula · A mão direita de Santo Estêvão · Interior de mármore e ouro",
"Banhos Széchenyi": "Piscinas quentes ao ar livre · Xadrez dentro d'água · Prédio amarelo neobarroco",
"Banhos Rudas": "Piscina octogonal turca do século XVI · Piscina no terraço com vista do Danúbio",
"Mercado Central": "Páprica, salames e foie gras · Lángos no andar de cima · Estrutura de ferro de 1897",
"Cruzeiro noturno": "Parlamento iluminado · Pontes e castelo acesos · Uma hora de passeio",
"Szimpla Kert": "O primeiro bar em ruínas · Móveis e objetos de todo tipo · Feira de produtores no domingo de manhã",
"Sapatos na Margem": "60 pares de sapatos de ferro · Memorial das vítimas de 1944–45 · Vista do castelo",
"Praça dos Heróis": "Colunata dos reis · Castelo Vajdahunyad · Lago que vira pista de gelo",
"Sinagoga da Rua Dohány": "A maior sinagoga da Europa · Árvore da Vida, de metal · Museu judaico",
"Ponte das Correntes": "Os leões de pedra · Vista do castelo e do Parlamento · Iluminada à noite",
"Ponte da Liberdade": "Ferro verde com aves Turul · Bondes amarelos · Bom lugar para o pôr do sol",
"Monte Gellért": "Estátua da Liberdade · Cidadela · A melhor vista do Danúbio",
"Igreja na Rocha": "Capela dentro da caverna · Mosteiro paulino · Entrada ao pé do morro",
"Avenida Andrássy": "Casarões e a Ópera · Lojas de marca · Termina na Praça dos Heróis",
"Ópera de Budapeste": "Escadaria de mármore · Salão dourado em ferradura · Visita com mini-concerto",
"Casa do Terror": "Tanque e parede de retratos no átrio · Celas no porão",
"Ilha Margarida": "Fonte musical · Jardim japonês · Ruínas de convento",
"Rua Váci": "Calçadão de lojas · Fachadas do século XIX · Vai até o Mercado Central",
"Praça da Liberdade": "Banco Nacional · Memorial soviético · Estátua de Reagan",
"Hospital na Rocha": "Enfermarias com bonecos de cera · Bunker nuclear da Guerra Fria",
"Biblioteca Szabó Ervin": "Salas do Palácio Wenckheim · Lustres e madeira entalhada · Poltronas para ler",
"New York Café": "Teto com afrescos · Colunas retorcidas e lustres · Música ao vivo",
"Gozsdu Udvar": "Sete pátios ligados · Bares e restaurantes · Feira de artesanato no fim de semana",
"Sinagoga da Rua Kazinczy": "Interior azul Art Nouveau · Fachada de tijolo",
"Museu de Belas Artes": "Salão românico restaurado · Mestres espanhóis e italianos · Coleção egípcia",
"Museu Nacional Húngaro": "Manto da coroação · Escadaria com afrescos",
"Museu de Etnografia": "Telhado-jardim aberto ao público · Fachada de pixels metálicos",
"Casa da Música": "Cobertura furada entre as árvores · Paredes de vidro · Exposição sonora",
"Várkert Bazár": "Jardins em terraços · Escadaria neorrenascentista · Vista do rio",
"Estação Nyugati": "Fachada de vidro e ferro · McDonald's num salão histórico",
"Metrô M1": "Estações de azulejo e madeira · Trens amarelos pequenos · Inaugurada em 1896",
"Banhos Lukács": "Piscinas termais ao ar livre · Placas de agradecimento no pátio · Frequentado por moradores",
"Mirante Erzsébet": "Torre de pedra a 527 m · Teleférico de cadeirinha · Vista de toda a cidade",
"Memento Park": "Estátuas gigantes de Lênin e Marx · As botas de Stalin · Trabant para a foto",
"Bate-volta Szentendre": "Ruelas coloridas · Igrejas sérvias · Museu do marzipã",
}


def sem_acento(s):
    import unicodedata
    return "".join(c for c in unicodedata.normalize("NFD", s or "") if unicodedata.category(c) != "Mn").lower()


def destaques_de(nome):
    n = sem_acento(nome)
    achou = [(len(k), v) for k, v in DESTAQUES.items() if n.startswith(sem_acento(k))]
    return max(achou)[1] if achou else ""
